swapFromAmount: '#swap-currency-input div[color="textSubtle"]'
swapInput: '#swap-currency-input .token-amount-input'
swapOutput: '#swap-currency-output .token-amount-input'
swapButton: '#swap-button'
confirmButton: '#confirm-swap-or-send'
swapInputToken: '#swap-currency-input #pair'
swapOutputToken: '#swap-currency-output #pair'
tokenSearchInput: '#token-search-input'
tokenSearchResult: 'div[class*="token-item-"]'
settingButton: '#open-settings-dialog-button-SWAP_LIQUIDITY'
inputSlippagetext: 'input[inputmode="decimal"]'
closeButton: 'button[aria-label="Close the dialog"]'
